// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(TiendaContext))]
    partial class TiendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Productos eléctricos para el hogar",
                            Eliminado = false,
                            Nombre = "Electrodomésticos"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Productos de limpieza",
                            Eliminado = false,
                            Nombre = "Limpieza"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Comestibles y bebidas",
                            Eliminado = false,
                            Nombre = "Alimentos"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Artículos de bazar",
                            Eliminado = false,
                            Nombre = "Bazar"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Juguetes y juegos",
                            Eliminado = false,
                            Nombre = "Juguetería"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Ropa y accesorios",
                            Eliminado = false,
                            Nombre = "Textil"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Herramientas y materiales",
                            Eliminado = false,
                            Nombre = "Ferretería"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Perfumes y cosméticos",
                            Eliminado = false,
                            Nombre = "Perfumería"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Útiles escolares y oficina",
                            Eliminado = false,
                            Nombre = "Papelería"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Productos para mascotas",
                            Eliminado = false,
                            Nombre = "Mascotas"
                        });
                });

            modelBuilder.Entity("Service.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("LocalidadId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Calle Falsa 123",
                            Dni = "30123456",
                            Eliminado = false,
                            Email = "juan.perez@email.com",
                            LocalidadId = 1,
                            Nombre = "Juan Pérez",
                            Telefono = "3511111111"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Av. Siempreviva 742",
                            Dni = "30234567",
                            Eliminado = false,
                            Email = "maria.gomez@email.com",
                            LocalidadId = 2,
                            Nombre = "María Gómez",
                            Telefono = "3512222222"
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "San Martín 100",
                            Dni = "30345678",
                            Eliminado = false,
                            Email = "carlos.lopez@email.com",
                            LocalidadId = 3,
                            Nombre = "Carlos López",
                            Telefono = "3513333333"
                        },
                        new
                        {
                            Id = 4,
                            Direccion = "Belgrano 200",
                            Dni = "30456789",
                            Eliminado = false,
                            Email = "ana.torres@email.com",
                            LocalidadId = 4,
                            Nombre = "Ana Torres",
                            Telefono = "3514444444"
                        },
                        new
                        {
                            Id = 5,
                            Direccion = "Rivadavia 300",
                            Dni = "30567890",
                            Eliminado = false,
                            Email = "luis.fernandez@email.com",
                            LocalidadId = 5,
                            Nombre = "Luis Fernández",
                            Telefono = "3515555555"
                        },
                        new
                        {
                            Id = 6,
                            Direccion = "Mitre 400",
                            Dni = "30678901",
                            Eliminado = false,
                            Email = "sofia.ramirez@email.com",
                            LocalidadId = 6,
                            Nombre = "Sofía Ramírez",
                            Telefono = "3516666666"
                        },
                        new
                        {
                            Id = 7,
                            Direccion = "Sarmiento 500",
                            Dni = "30789012",
                            Eliminado = false,
                            Email = "diego.castro@email.com",
                            LocalidadId = 7,
                            Nombre = "Diego Castro",
                            Telefono = "3517777777"
                        },
                        new
                        {
                            Id = 8,
                            Direccion = "Urquiza 600",
                            Dni = "30890123",
                            Eliminado = false,
                            Email = "lucia.martinez@email.com",
                            LocalidadId = 8,
                            Nombre = "Lucía Martínez",
                            Telefono = "3518888888"
                        },
                        new
                        {
                            Id = 9,
                            Direccion = "Lavalle 700",
                            Dni = "30901234",
                            Eliminado = false,
                            Email = "javier.ruiz@email.com",
                            LocalidadId = 9,
                            Nombre = "Javier Ruiz",
                            Telefono = "3519999999"
                        },
                        new
                        {
                            Id = 10,
                            Direccion = "Moreno 800",
                            Dni = "31012345",
                            Eliminado = false,
                            Email = "valeria.diaz@email.com",
                            LocalidadId = 10,
                            Nombre = "Valeria Díaz",
                            Telefono = "3511010101"
                        });
                });

            modelBuilder.Entity("Service.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FormaDePago")
                        .HasColumnType("int");

                    b.Property<int>("Iva")
                        .HasColumnType("int");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Compras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 10, 21, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(950),
                            FormaDePago = 0,
                            Iva = 21,
                            ProveedorId = 1,
                            Total = 120000
                        },
                        new
                        {
                            Id = 2,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 10, 22, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(973),
                            FormaDePago = 1,
                            Iva = 21,
                            ProveedorId = 2,
                            Total = 180000
                        },
                        new
                        {
                            Id = 3,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 10, 23, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(975),
                            FormaDePago = 3,
                            Iva = 21,
                            ProveedorId = 3,
                            Total = 1200
                        },
                        new
                        {
                            Id = 4,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 10, 24, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(977),
                            FormaDePago = 0,
                            Iva = 21,
                            ProveedorId = 4,
                            Total = 800
                        },
                        new
                        {
                            Id = 5,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 10, 25, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(979),
                            FormaDePago = 2,
                            Iva = 21,
                            ProveedorId = 5,
                            Total = 1500
                        },
                        new
                        {
                            Id = 6,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 10, 26, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(980),
                            FormaDePago = 3,
                            Iva = 21,
                            ProveedorId = 6,
                            Total = 3500
                        },
                        new
                        {
                            Id = 7,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 10, 27, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(982),
                            FormaDePago = 0,
                            Iva = 21,
                            ProveedorId = 7,
                            Total = 9000
                        },
                        new
                        {
                            Id = 8,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 10, 28, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(984),
                            FormaDePago = 1,
                            Iva = 21,
                            ProveedorId = 8,
                            Total = 2500
                        },
                        new
                        {
                            Id = 9,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 10, 29, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(985),
                            FormaDePago = 2,
                            Iva = 21,
                            ProveedorId = 9,
                            Total = 5000
                        },
                        new
                        {
                            Id = 10,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 10, 30, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(987),
                            FormaDePago = 0,
                            Iva = 21,
                            ProveedorId = 10,
                            Total = 7000
                        });
                });

            modelBuilder.Entity("Service.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesCompra");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            CompraId = 1,
                            Eliminado = false,
                            PrecioUnitario = 120000m,
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            CompraId = 2,
                            Eliminado = false,
                            PrecioUnitario = 180000m,
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 1,
                            CompraId = 3,
                            Eliminado = false,
                            PrecioUnitario = 1200m,
                            ProductoId = 3
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 1,
                            CompraId = 4,
                            Eliminado = false,
                            PrecioUnitario = 800m,
                            ProductoId = 4
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 1,
                            CompraId = 5,
                            Eliminado = false,
                            PrecioUnitario = 1500m,
                            ProductoId = 5
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 1,
                            CompraId = 6,
                            Eliminado = false,
                            PrecioUnitario = 3500m,
                            ProductoId = 6
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 1,
                            CompraId = 7,
                            Eliminado = false,
                            PrecioUnitario = 9000m,
                            ProductoId = 7
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 1,
                            CompraId = 8,
                            Eliminado = false,
                            PrecioUnitario = 2500m,
                            ProductoId = 8
                        },
                        new
                        {
                            Id = 9,
                            Cantidad = 1,
                            CompraId = 9,
                            Eliminado = false,
                            PrecioUnitario = 5000m,
                            ProductoId = 9
                        },
                        new
                        {
                            Id = 10,
                            Cantidad = 1,
                            CompraId = 10,
                            Eliminado = false,
                            PrecioUnitario = 7000m,
                            ProductoId = 10
                        });
                });

            modelBuilder.Entity("Service.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            Eliminado = false,
                            PrecioUnitario = 120000m,
                            ProductoId = 1,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            Eliminado = false,
                            PrecioUnitario = 180000m,
                            ProductoId = 2,
                            VentaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 1,
                            Eliminado = false,
                            PrecioUnitario = 1200m,
                            ProductoId = 3,
                            VentaId = 3
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 1,
                            Eliminado = false,
                            PrecioUnitario = 800m,
                            ProductoId = 4,
                            VentaId = 4
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 1,
                            Eliminado = false,
                            PrecioUnitario = 1500m,
                            ProductoId = 5,
                            VentaId = 5
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 1,
                            Eliminado = false,
                            PrecioUnitario = 3500m,
                            ProductoId = 6,
                            VentaId = 6
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 1,
                            Eliminado = false,
                            PrecioUnitario = 9000m,
                            ProductoId = 7,
                            VentaId = 7
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 1,
                            Eliminado = false,
                            PrecioUnitario = 2500m,
                            ProductoId = 8,
                            VentaId = 8
                        },
                        new
                        {
                            Id = 9,
                            Cantidad = 1,
                            Eliminado = false,
                            PrecioUnitario = 5000m,
                            ProductoId = 9,
                            VentaId = 9
                        },
                        new
                        {
                            Id = 10,
                            Cantidad = 1,
                            Eliminado = false,
                            PrecioUnitario = 7000m,
                            ProductoId = 10,
                            VentaId = 10
                        });
                });

            modelBuilder.Entity("Service.Models.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Localidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eliminado = false,
                            Nombre = "Córdoba"
                        },
                        new
                        {
                            Id = 2,
                            Eliminado = false,
                            Nombre = "Villa María"
                        },
                        new
                        {
                            Id = 3,
                            Eliminado = false,
                            Nombre = "Río Cuarto"
                        },
                        new
                        {
                            Id = 4,
                            Eliminado = false,
                            Nombre = "San Francisco"
                        },
                        new
                        {
                            Id = 5,
                            Eliminado = false,
                            Nombre = "Alta Gracia"
                        },
                        new
                        {
                            Id = 6,
                            Eliminado = false,
                            Nombre = "Carlos Paz"
                        },
                        new
                        {
                            Id = 7,
                            Eliminado = false,
                            Nombre = "Jesús María"
                        },
                        new
                        {
                            Id = 8,
                            Eliminado = false,
                            Nombre = "Villa Dolores"
                        },
                        new
                        {
                            Id = 9,
                            Eliminado = false,
                            Nombre = "La Falda"
                        },
                        new
                        {
                            Id = 10,
                            Eliminado = false,
                            Nombre = "Cosquín"
                        });
                });

            modelBuilder.Entity("Service.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eliminado = false,
                            Nombre = "Philips"
                        },
                        new
                        {
                            Id = 2,
                            Eliminado = false,
                            Nombre = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            Eliminado = false,
                            Nombre = "LG"
                        },
                        new
                        {
                            Id = 4,
                            Eliminado = false,
                            Nombre = "Ariel"
                        },
                        new
                        {
                            Id = 5,
                            Eliminado = false,
                            Nombre = "Coca-Cola"
                        },
                        new
                        {
                            Id = 6,
                            Eliminado = false,
                            Nombre = "Tupperware"
                        },
                        new
                        {
                            Id = 7,
                            Eliminado = false,
                            Nombre = "Mattel"
                        },
                        new
                        {
                            Id = 8,
                            Eliminado = false,
                            Nombre = "Levis"
                        },
                        new
                        {
                            Id = 9,
                            Eliminado = false,
                            Nombre = "Tramontina"
                        },
                        new
                        {
                            Id = 10,
                            Eliminado = false,
                            Nombre = "Nestlé"
                        });
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Imagen")
                        .HasColumnType("longtext");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Oferta")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Smart TV Philips",
                            Eliminado = false,
                            Imagen = "tv32.jpg",
                            MarcaId = 1,
                            Nombre = "Televisor LED 32",
                            Oferta = true,
                            Precio = 120000m,
                            ProveedorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descripcion = "Samsung 7kg",
                            Eliminado = false,
                            Imagen = "lavadora.jpg",
                            MarcaId = 2,
                            Nombre = "Lavadora Automática",
                            Oferta = false,
                            Precio = 180000m,
                            ProveedorId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Descripcion = "1L",
                            Eliminado = false,
                            Imagen = "ariel.jpg",
                            MarcaId = 4,
                            Nombre = "Detergente Ariel",
                            Oferta = false,
                            Precio = 1200m,
                            ProveedorId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            Descripcion = "Bebida gaseosa",
                            Eliminado = false,
                            Imagen = "cocacola.jpg",
                            MarcaId = 5,
                            Nombre = "Coca-Cola 2L",
                            Oferta = true,
                            Precio = 800m,
                            ProveedorId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 4,
                            Descripcion = "Contenedor plástico",
                            Eliminado = false,
                            Imagen = "tupperware.jpg",
                            MarcaId = 6,
                            Nombre = "Tupperware Grande",
                            Oferta = false,
                            Precio = 1500m,
                            ProveedorId = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 5,
                            Descripcion = "Mattel original",
                            Eliminado = false,
                            Imagen = "barbie.jpg",
                            MarcaId = 7,
                            Nombre = "Muñeca Barbie",
                            Oferta = true,
                            Precio = 3500m,
                            ProveedorId = 6
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 6,
                            Descripcion = "Talle 42",
                            Eliminado = false,
                            Imagen = "levis.jpg",
                            MarcaId = 8,
                            Nombre = "Jeans Levis",
                            Oferta = false,
                            Precio = 9000m,
                            ProveedorId = 7
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 7,
                            Descripcion = "Acero forjado",
                            Eliminado = false,
                            Imagen = "martillo.jpg",
                            MarcaId = 9,
                            Nombre = "Martillo Tramontina",
                            Oferta = false,
                            Precio = 2500m,
                            ProveedorId = 8
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 8,
                            Descripcion = "Fragancia floral",
                            Eliminado = false,
                            Imagen = "perfume.jpg",
                            MarcaId = 10,
                            Nombre = "Perfume Nestlé",
                            Oferta = true,
                            Precio = 5000m,
                            ProveedorId = 9
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 10,
                            Descripcion = "Bolsa 10kg",
                            Eliminado = false,
                            Imagen = "mascotas.jpg",
                            MarcaId = 10,
                            Nombre = "Alimento Mascotas",
                            Oferta = false,
                            Precio = 7000m,
                            ProveedorId = 10
                        });
                });

            modelBuilder.Entity("Service.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondicionIva")
                        .HasColumnType("int");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LocalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefonos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CondicionIva = 0,
                            Cuit = "20-12345678-1",
                            Direccion = "Av. Colón 123",
                            Eliminado = false,
                            LocalidadId = 1,
                            Nombre = "Distribuidora Sur",
                            Telefonos = "3511234567"
                        },
                        new
                        {
                            Id = 2,
                            CondicionIva = 5,
                            Cuit = "20-23456789-2",
                            Direccion = "San Martín 456",
                            Eliminado = false,
                            LocalidadId = 2,
                            Nombre = "Mayorista Norte",
                            Telefonos = "3512345678"
                        },
                        new
                        {
                            Id = 3,
                            CondicionIva = 4,
                            Cuit = "20-34567890-3",
                            Direccion = "Belgrano 789",
                            Eliminado = false,
                            LocalidadId = 3,
                            Nombre = "Almacén Central",
                            Telefonos = "3513456789"
                        },
                        new
                        {
                            Id = 4,
                            CondicionIva = 1,
                            Cuit = "20-45678901-4",
                            Direccion = "Rivadavia 321",
                            Eliminado = false,
                            LocalidadId = 4,
                            Nombre = "Mercado Oeste",
                            Telefonos = "3514567890"
                        },
                        new
                        {
                            Id = 5,
                            CondicionIva = 2,
                            Cuit = "20-56789012-5",
                            Direccion = "Mitre 654",
                            Eliminado = false,
                            LocalidadId = 5,
                            Nombre = "Distribuidora Este",
                            Telefonos = "3515678901"
                        },
                        new
                        {
                            Id = 6,
                            CondicionIva = 3,
                            Cuit = "20-67890123-6",
                            Direccion = "Sarmiento 987",
                            Eliminado = false,
                            LocalidadId = 6,
                            Nombre = "Mayorista Sur",
                            Telefonos = "3516789012"
                        },
                        new
                        {
                            Id = 7,
                            CondicionIva = 6,
                            Cuit = "20-78901234-7",
                            Direccion = "Urquiza 159",
                            Eliminado = false,
                            LocalidadId = 7,
                            Nombre = "Almacén Norte",
                            Telefonos = "3517890123"
                        },
                        new
                        {
                            Id = 8,
                            CondicionIva = 5,
                            Cuit = "20-89012345-8",
                            Direccion = "Lavalle 753",
                            Eliminado = false,
                            LocalidadId = 8,
                            Nombre = "Mercado Central",
                            Telefonos = "3518901234"
                        },
                        new
                        {
                            Id = 9,
                            CondicionIva = 0,
                            Cuit = "20-90123456-9",
                            Direccion = "Moreno 357",
                            Eliminado = false,
                            LocalidadId = 9,
                            Nombre = "Distribuidora Norte",
                            Telefonos = "3519012345"
                        },
                        new
                        {
                            Id = 10,
                            CondicionIva = 4,
                            Cuit = "20-01234567-0",
                            Direccion = "Alvear 951",
                            Eliminado = false,
                            LocalidadId = 10,
                            Nombre = "Mayorista Central",
                            Telefonos = "3510123456"
                        });
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FormaPago")
                        .HasColumnType("int");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 10, 31, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(1027),
                            FormaPago = 0,
                            Iva = 21m,
                            Total = 120000m
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 11, 1, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(1032),
                            FormaPago = 1,
                            Iva = 21m,
                            Total = 180000m
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 3,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 11, 2, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(1034),
                            FormaPago = 3,
                            Iva = 21m,
                            Total = 1200m
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 4,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 11, 3, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(1036),
                            FormaPago = 0,
                            Iva = 21m,
                            Total = 800m
                        },
                        new
                        {
                            Id = 5,
                            ClienteId = 5,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 11, 4, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(1039),
                            FormaPago = 2,
                            Iva = 21m,
                            Total = 1500m
                        },
                        new
                        {
                            Id = 6,
                            ClienteId = 6,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 11, 5, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(1042),
                            FormaPago = 3,
                            Iva = 21m,
                            Total = 3500m
                        },
                        new
                        {
                            Id = 7,
                            ClienteId = 7,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 11, 6, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(1044),
                            FormaPago = 0,
                            Iva = 21m,
                            Total = 9000m
                        },
                        new
                        {
                            Id = 8,
                            ClienteId = 8,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 11, 7, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(1045),
                            FormaPago = 1,
                            Iva = 21m,
                            Total = 2500m
                        },
                        new
                        {
                            Id = 9,
                            ClienteId = 9,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 11, 8, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(1048),
                            FormaPago = 2,
                            Iva = 21m,
                            Total = 5000m
                        },
                        new
                        {
                            Id = 10,
                            ClienteId = 10,
                            Eliminado = false,
                            Fecha = new DateTime(2025, 11, 9, 17, 49, 3, 404, DateTimeKind.Local).AddTicks(1050),
                            FormaPago = 0,
                            Iva = 21m,
                            Total = 7000m
                        });
                });

            modelBuilder.Entity("Service.Models.Cliente", b =>
                {
                    b.HasOne("Service.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("Service.Models.Compra", b =>
                {
                    b.HasOne("Service.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Service.Models.DetalleCompra", b =>
                {
                    b.HasOne("Service.Models.Compra", "Compra")
                        .WithMany()
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Service.Models.DetalleVenta", b =>
                {
                    b.HasOne("Service.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.HasOne("Service.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Service.Models.Proveedor", b =>
                {
                    b.HasOne("Service.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.HasOne("Service.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.Navigation("DetallesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
